package form;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import swing.EventLogin;

public class Home extends javax.swing.JPanel {
    Codes codes = new Codes();
    public static ArrayList<Integer> studentNo = new ArrayList<Integer>();
    
    public static ArrayList<String> studentInfo = new ArrayList<>();
    private EventLogin event;
    
    public Home() {
        initComponents();
        tableDark1.fixTable(jScrollPane1);
        tableDark2.fixTable(jScrollPane2);
        
        /*int No = studentNo.get(0);
        studentInfo = codes.FetchStudentInfo(No);
        
        if(!studentInfo.isEmpty()){
            String Number = studentInfo.get(0);
            String name = studentInfo.get(1);
            String surname = studentInfo.get(2);
            String dp = studentInfo.get(3);
            String lv = studentInfo.get(4);
            switch(dp){
                case "Bilgisayar Muhendisligi": dp = "Bil.Müh.";
                break;
                case "Elektrik Elektronik Muhendisligi": dp = "E.E.Müh.";
                break;
                case "Yazilim Muhendisligi": dp = "Yaz.Müh.";
                break;
                default: dp = "null";
            }
            
            namesurnameText.setText(name+" "+surname);
            noText.setText(Number);
            dplvText.setText(dp+" "+lv+".Sınıf");
            
        }else{
        namesurnameText.setText("null");
        noText.setText("null");
        dplvText.setText("null");
        }*/
        
    }

    public void setEventLogin(EventLogin event) {
        this.event = event;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialTabbed1 = new form.MaterialTabbed();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        button4 = new swing.Button();
        namesurnameText = new swing.TextField();
        noText = new swing.TextField();
        dplvText = new swing.TextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDark2 = new form.TableDark();
        textAreaScroll1 = new swing.TextAreaScroll();
        textArea1 = new swing.TextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        button7 = new swing.Button();
        jLabel8 = new javax.swing.JLabel();
        namesurnameText1 = new swing.TextField();
        noText1 = new swing.TextField();
        dplvText1 = new swing.TextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDark1 = new form.TableDark();
        textFieldSuggestion7 = new swing.TextFieldSuggestion();
        textFieldSuggestion4 = new swing.TextFieldSuggestion();
        button2 = new swing.Button();
        button3 = new swing.Button();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        button8 = new swing.Button();
        jLabel9 = new javax.swing.JLabel();
        namesurnameText2 = new swing.TextField();
        noText2 = new swing.TextField();
        dplvText2 = new swing.TextField();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDark3 = new form.TableDark();
        namesurnameText3 = new swing.TextField();
        namesurnameText4 = new swing.TextField();
        namesurnameText5 = new swing.TextField();
        textAreaScroll2 = new swing.TextAreaScroll();
        textArea2 = new swing.TextArea();
        button1 = new swing.Button();

        setBackground(new java.awt.Color(245, 245, 245));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        materialTabbed1.setBackground(java.awt.Color.darkGray);
        materialTabbed1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                materialTabbed1MouseMoved(evt);
            }
        });
        materialTabbed1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                materialTabbed1MousePressed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 542));

        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit2.png"))); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        namesurnameText.setForeground(new java.awt.Color(255, 255, 255));
        namesurnameText.setText("Ad Soyad");
        namesurnameText.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        namesurnameText.setEnabled(false);
        namesurnameText.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        noText.setForeground(new java.awt.Color(255, 255, 255));
        noText.setText("No");
        noText.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        noText.setEnabled(false);
        noText.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        dplvText.setForeground(new java.awt.Color(255, 255, 255));
        dplvText.setText("Bolum Sınıf");
        dplvText.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dplvText.setEnabled(false);
        dplvText.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namesurnameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(noText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dplvText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namesurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dplvText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(java.awt.Color.lightGray);

        tableDark2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ödev Adı", "Not", "Durum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableDark2);
        if (tableDark2.getColumnModel().getColumnCount() > 0) {
            tableDark2.getColumnModel().getColumn(0).setResizable(false);
            tableDark2.getColumnModel().getColumn(0).setPreferredWidth(500);
            tableDark2.getColumnModel().getColumn(1).setResizable(false);
            tableDark2.getColumnModel().getColumn(1).setPreferredWidth(50);
            tableDark2.getColumnModel().getColumn(2).setResizable(false);
            tableDark2.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        textAreaScroll1.setLabelText("Açıklama");

        textArea1.setColumns(20);
        textArea1.setRows(5);
        textArea1.setEnabled(false);
        textAreaScroll1.setViewportView(textArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                    .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAreaScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        materialTabbed1.addTab("Profil", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(java.awt.Color.darkGray);
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 542));

        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit2.png"))); // NOI18N
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        namesurnameText1.setForeground(new java.awt.Color(255, 255, 255));
        namesurnameText1.setText("Ad Soyad");
        namesurnameText1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        namesurnameText1.setEnabled(false);
        namesurnameText1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        noText1.setForeground(new java.awt.Color(255, 255, 255));
        noText1.setText("No");
        noText1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        noText1.setEnabled(false);
        noText1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        dplvText1.setForeground(new java.awt.Color(255, 255, 255));
        dplvText1.setText("Bolum Sınıf");
        dplvText1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dplvText1.setEnabled(false);
        dplvText1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(namesurnameText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dplvText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namesurnameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noText1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dplvText1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel3.add(jPanel10, java.awt.BorderLayout.LINE_START);

        jPanel12.setBackground(java.awt.Color.lightGray);

        tableDark1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ödev", "Başlangıç", "Bitiş", "Kontrol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDark1);
        if (tableDark1.getColumnModel().getColumnCount() > 0) {
            tableDark1.getColumnModel().getColumn(0).setResizable(false);
            tableDark1.getColumnModel().getColumn(0).setPreferredWidth(300);
            tableDark1.getColumnModel().getColumn(1).setResizable(false);
            tableDark1.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableDark1.getColumnModel().getColumn(2).setResizable(false);
            tableDark1.getColumnModel().getColumn(2).setPreferredWidth(100);
            tableDark1.getColumnModel().getColumn(3).setResizable(false);
        }

        textFieldSuggestion7.setForeground(java.awt.Color.black);
        textFieldSuggestion7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldSuggestion7.setText("Ödev Yükle");
        textFieldSuggestion7.setEnabled(false);
        textFieldSuggestion7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N

        textFieldSuggestion4.setForeground(new java.awt.Color(0, 0, 0));
        textFieldSuggestion4.setText("Dosya");
        textFieldSuggestion4.setEnabled(false);

        button2.setBackground(java.awt.Color.gray);
        button2.setText("Dosya Yükle");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(java.awt.Color.darkGray);
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("Ödevi Yükle");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(textFieldSuggestion4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(textFieldSuggestion7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(textFieldSuggestion7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldSuggestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel12, java.awt.BorderLayout.CENTER);

        materialTabbed1.addTab("Ödev Yükle", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(java.awt.Color.darkGray);
        jPanel11.setPreferredSize(new java.awt.Dimension(150, 542));

        button8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit2.png"))); // NOI18N
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        namesurnameText2.setForeground(new java.awt.Color(255, 255, 255));
        namesurnameText2.setText("Ad Soyad");
        namesurnameText2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        namesurnameText2.setEnabled(false);
        namesurnameText2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        noText2.setForeground(new java.awt.Color(255, 255, 255));
        noText2.setText("No");
        noText2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        noText2.setEnabled(false);
        noText2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        dplvText2.setForeground(new java.awt.Color(255, 255, 255));
        dplvText2.setText("Bolum Sınıf");
        dplvText2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dplvText2.setEnabled(false);
        dplvText2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(namesurnameText2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dplvText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namesurnameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noText2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dplvText2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel4.add(jPanel11, java.awt.BorderLayout.LINE_START);

        jPanel13.setBackground(java.awt.Color.lightGray);

        tableDark3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ödev Adı", "Not", "Durum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableDark3);
        if (tableDark3.getColumnModel().getColumnCount() > 0) {
            tableDark3.getColumnModel().getColumn(0).setResizable(false);
            tableDark3.getColumnModel().getColumn(0).setPreferredWidth(500);
            tableDark3.getColumnModel().getColumn(1).setResizable(false);
            tableDark3.getColumnModel().getColumn(1).setPreferredWidth(50);
            tableDark3.getColumnModel().getColumn(2).setResizable(false);
            tableDark3.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        namesurnameText3.setForeground(new java.awt.Color(255, 255, 255));
        namesurnameText3.setText("Konu >");
        namesurnameText3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        namesurnameText3.setEnabled(false);
        namesurnameText3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        namesurnameText4.setForeground(new java.awt.Color(0, 0, 0));
        namesurnameText4.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        namesurnameText4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        namesurnameText5.setForeground(new java.awt.Color(255, 255, 255));
        namesurnameText5.setText("Mesajınız >");
        namesurnameText5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        namesurnameText5.setEnabled(false);
        namesurnameText5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        textAreaScroll2.setLabelText("Açıklama");

        textArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textArea2.setColumns(20);
        textArea2.setRows(5);
        textAreaScroll2.setViewportView(textArea2);

        button1.setText("Gönder");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(namesurnameText3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(namesurnameText4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(namesurnameText5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textAreaScroll2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namesurnameText3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namesurnameText4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(namesurnameText5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textAreaScroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel13, java.awt.BorderLayout.CENTER);

        materialTabbed1.addTab("İletişim", jPanel4);

        add(materialTabbed1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        event.logOut();
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        event.logOut();
    }//GEN-LAST:event_button8ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        event.logOut();
    }//GEN-LAST:event_button4ActionPerformed

    private void materialTabbed1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialTabbed1MousePressed
        //System.out.println(materialTabbed1.getSelectedIndex());
    }//GEN-LAST:event_materialTabbed1MousePressed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
    }//GEN-LAST:event_button2ActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        
    }//GEN-LAST:event_formMouseEntered

    private void materialTabbed1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialTabbed1MouseMoved
        if(materialTabbed1.getSelectedIndex()==0){
            int No = studentNo.get(0);
            studentInfo = codes.FetchStudentInfo(No);

            if(!studentInfo.isEmpty()){
                String Number = studentInfo.get(0);
                String name = studentInfo.get(1);
                String surname = studentInfo.get(2);
                String dp = studentInfo.get(3);
                String lv = studentInfo.get(4);
                switch(dp){
                    case "Bilgisayar Muhendisligi": dp = "Bil.Müh.";
                    break;
                    case "Elektrik Elektronik Muhendisligi": dp = "E.E.Müh.";
                    break;
                    case "Yazilim Muhendisligi": dp = "Yaz.Müh.";
                    break;
                    default: dp = "null";
                }

                namesurnameText.setText(name+" "+surname);
                noText.setText(Number);
                dplvText.setText(dp+" "+lv+".Sınıf");
                namesurnameText1.setText(name+" "+surname);
                noText1.setText(Number);
                dplvText1.setText(dp+" "+lv+".Sınıf");
                namesurnameText2.setText(name+" "+surname);
                noText2.setText(Number);
                dplvText2.setText(dp+" "+lv+".Sınıf");

            }else{
            namesurnameText.setText("null");
            noText.setText("null");
            dplvText.setText("null");
            namesurnameText1.setText("null");
            noText1.setText("null");
            dplvText1.setText("null");
            namesurnameText2.setText("null");
            noText2.setText("null");
            dplvText2.setText("null");
            }
        }
        
        
    }//GEN-LAST:event_materialTabbed1MouseMoved
    public void getNo(int No){
        studentNo.add(No);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button button1;
    private swing.Button button2;
    private swing.Button button3;
    private swing.Button button4;
    private swing.Button button7;
    private swing.Button button8;
    private swing.TextField dplvText;
    private swing.TextField dplvText1;
    private swing.TextField dplvText2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private form.MaterialTabbed materialTabbed1;
    private swing.TextField namesurnameText;
    private swing.TextField namesurnameText1;
    private swing.TextField namesurnameText2;
    private swing.TextField namesurnameText3;
    private swing.TextField namesurnameText4;
    private swing.TextField namesurnameText5;
    private swing.TextField noText;
    private swing.TextField noText1;
    private swing.TextField noText2;
    private form.TableDark tableDark1;
    private form.TableDark tableDark2;
    private form.TableDark tableDark3;
    private swing.TextArea textArea1;
    private swing.TextArea textArea2;
    private swing.TextAreaScroll textAreaScroll1;
    private swing.TextAreaScroll textAreaScroll2;
    private swing.TextFieldSuggestion textFieldSuggestion4;
    private swing.TextFieldSuggestion textFieldSuggestion7;
    // End of variables declaration//GEN-END:variables
}
